# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WJAsyncExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WJAsyncExample
  pod 'WJAsync', '~> 0.0'

  target 'WJAsyncExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WJAsyncExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
